branches:
  only:
  - master

language: groovy

matrix:
  include:
  - os: linux
    jdk: oraclejdk8
  - os: osx # OSX 10.10
    osx_image: xcode6.4
  - os: osx # OSX 10.11
    osx_image: xcode8
  - os: osx # OSX 10.12
    osx_image: xcode9
  - os: osx # OSX 10.13

addons:
  apt:
    packages:
    - libatlas3-base

script: ./gradlew check --info

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
